function mk(x,cpu,ci){const c=CH[ci];return{x,y:0,vy:0,vx:0,face:cpu?-1:1,hp:Math.round(c.hp*HPK),mhp:Math.round(c.hp*HPK),gauge:0,st:'i',at:0,ty:'L',hit:0,hl:[],sp:0,stun:0,gt:0,gcd:0,inv:0,dn:0,th:0,acc:0,acct:0,chain:0,combo:0,ct:0,wp:0,mv:0,fl:0,cpu,c,in:{l:0,r:0,u:0,d:0,g:0,hx:0,ha:0},cr:0,err:0,pd:[0,0,0,0],pbk:[0,0,0,0],arms:0,legs:0,gu:0,spin:0,gv:0,gF:null,rw:0,pm:0,ra:0,alt:0,trl:[],dsh:0,dsd:0,dfw:0,pl:0,pr:0,lk:'',lt:-99,bz:0,stc:0,lag:0,gr:0,grt:0,ht:0,adu:0,ads:0,chv:0,chm:0,cht:0}}
function start(re){A=mk(200,SPECT,ch);A.face=1;const oi=re&&lastOpp!=null?lastOpp:VS2?ch2:selC?selC-1:(ch+1+(Math.random()*(CH.length-1)|0))%CH.length;lastOpp=oi;B=mk(480,!VS2,oi);B.face=-1;T=0;SG=re&&lastSG!=null?lastSG:selV?selV-1:Math.random()*STG.length|0;lastSG=SG;ST={mc:0,par:0,brk:0,fr:0};endT=0;parts=[];texts=[];PJ=[];RG=[];SPX=[];DEB=[];CI=null;tut=null;/* v57 CPUの色は試合ごとに4色から抽選。同キャラ戦は相手と別の色。「もう一度」は前の試合の色のまま */if(re&&lastCol){A.alt=lastCol[0];B.alt=lastCol[1]}else if(VS2){A.alt=colOf(ch);B.alt=v2col()}else{A.alt=SPECT?Math.random()*NCOL|0:colOf(ch);B.alt=oi==ch?(A.alt+1+(Math.random()*(NCOL-1)|0))%NCOL:Math.random()*NCOL|0}lastCol=[A.alt,B.alt];tutM=false;paused=false;rn=1;rt=5400;introT=100;hstop=0;mode='intro';grudge();sfx(introT>100?'rival':'round',GR&&GR.cv);try{localStorage.setItem('nf2_lv',lv);localStorage.setItem('nf2_ch',ch)}catch(e){}try{window.NFA&&NFA.matchStart({character:CH[ch].n,opponent:CH[oi].n,level:lv,spectate:SPECT?1:0,rematch:re?1:0,lang:LANG,mode:VS2?'vs2p':'cpu'})}catch(e){}}
function resetRound(){[A,B].forEach((f,i)=>{Object.assign(f,{gr:0,grt:0,adu:0,ads:0,chv:0,chm:0,cht:0,stc:0,bl:0,dju:0,ps:null,dsh:0,bz:0,spin:0,gu:0,gv:0,gF:null,x:i?480:200,y:0,vy:0,vx:0,hp:f.mhp,st:'i',stun:0,inv:0,combo:0,at:0,gt:0,th:0,dn:0,acc:0,chain:0,fl:0,lag:0,jg:0,bq:null});f.face=i?-1:1});PJ=[];RG=[];SPX=[];hstop=0;rn++;rt=5400;introT=100;mode='intro';sfx('round')}
function pop(t,x,y,c){if(tut&&t=='OK!')texts.push({t,x,y,l:1,c})}
function burst(x,y,h){for(let i=0;i<12;i++){const a=Math.random()*6.28,s=1+Math.random()*4;parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:1,h})}}
const gain=(f,n)=>{f.gauge=Math.min(28,f.gauge+n)};
function fx2(a,d,dm,ex,px,py){const hv=(ex.heal!=null?ex.heal:(a.c.ls||0))*(a.c.mist&&d.bl>0?1.5:1);if(hv>0&&a.hp>0&&dm>0){const h=Math.min(a.mhp-a.hp,dm*hv);if(h>0){a.hp+=h;if(h>=1){pop('+'+Math.round(h),a.x,GY-a.y-115,'#ff5a9a');if(a.c.mist)drainFx(a,px,py)}}}
if(ex.bleed&&d.hp>0){d.bl=ex.bleed[0];d.bld=ex.bleed[1];d.blt=0;pop(d.c.mech?'漏電':'出血',px,py-30,d.c.mech?'#7fe8ff':'#ff3d7f')}}
function drainFx(a,x,y){if(SPX.filter(e=>e.k=='drain').length<3)SPX.push({k:'drain',f:a,sx:x,sy:y,t:0,col:'#ff3d7f'})}
function mistFx(f){SPX.push({k:'mist',x:f.x,y:f.y,t:0,col:fcol(f)})}
function tickFx(f,o){if(f.bl>0&&f.st!='down'&&f.hp>0){if(++f.blt>=30){f.blt=0;f.bl--;f.hp-=f.bld;burst(f.x,GY-f.y-50,f.c.mech?190:340);if(f.hp<=0){f.hp=0;f.bl=0;ko(f)}}}}
function ko(d,tm){if(tut){if(d===B&&d.hp<d.mhp*.5)tut.adj+=d.mhp*.5-d.hp;d.hp=Math.max(d.hp,d.mhp*.5);return}if(mode!='play')return;shake=20;sfx('ko');const w=d===A?B:A;w.rw++;koTm=tm?1:0;koPerfect=!tm&&w.hp>=w.mhp-.01?1:0;hstop=0;ring(d.x,GY-d.y-50,'#f57',1);if(!tm&&d.st!='fall'&&d.st!='down'){d.st='fall';d.vy=Math.max(d.vy,5);d.vx=(d.x>w.x?1:-1)*5;d.th=0;d.spin=0}d.hp=Math.max(0,d.hp);koV=d;koT=0;koFinal=w.rw>=2?1:0;if(koFinal){win=d===A?'LOSE':'WIN';recEnd();try{window.NFA&&NFA.matchEnd({result:koTm?'TIMEUP_'+win:win,rounds:A.rw+B.rw})}catch(e){}}mode='ko';kt=koFinal?64:48}
function hitRes(a,d,dm,hs,kb,gg,lau,gb,ex){ex=ex||{};if(d.inv>0||mode!='play'||d.st=='down')return false;const jg=d.st=='fall';if(jg&&(d.y<=JGY||(d.jg||0)>=JGM))return false;const dir=d.x>a.x?1:-1,px=d.x,py=GY-d.y-60,Pd=d.st=='atk'?MV(d):null;dm*=pm(a,ex);if(a.c.stg)dm*=[1,1.1,1.2][a.stc||0];if(d.c.stg&&d.stc>=2)dm*=1.1;if(a.bz>0)dm*=1.3;if(d.bz>0)dm*=1.1;
if(Pd&&Pd.ctr&&d.at>=Pd.su&&d.at<Pd.su+Pd.ac&&Math.abs(a.x-d.x)<110){a.hp-=Pd.cd;a.st='fall';a.vy=7;a.vx=-dir*7;a.th=0;a.acc=0;gain(d,2);EV('ctr',a,d,ex);d.at=Pd.su+Pd.ac;pop('COUNTER!',px,py-60,'#ff6');burst(px,py,50);shake=14;hstop=8;ring(px,py,'#ff6',1);sfx('counter');if(a.hp<=0)ko(a);return true}
if(Pd&&Pd.arm&&d.at>=Pd.su-8&&d.at<Pd.su+Pd.ac&&!lau){d.hp-=dm*.6;fx2(a,d,dm*.6,ex,px,py);limbHit(d,dm*.6,'mid',ex.cut);gain(d,1);gain(a,gg);EV('arm',a,d,ex);pop('ARMOR',px,py-50,'#9cf');hstop=Math.max(hstop,3);burst(px,py,200);shake=Math.max(shake,5);sfx('armor');if(d.hp<=0)ko(d);return true}
if(d.st=='guard'&&d.y<=0&&!gb&&!(lowFlag&&!d.cr)){if(d.gt<=PW){a.st='hurt';a.stun=40;a.vx=-dir*6;gain(d,2);EV('pry',a,d,ex);if((d===A||VS2)&&ST&&!tut)ST.par++;pop('PARRY!',px,py-40,'#5f5');if(tut&&d===A)tut.c.blk++;hstop=Math.max(hstop,6);ring(px,py,'#5f5');burst(px,py,120);shake=8;sfx('parry');return true}
d.hp-=Math.ceil(dm*.2);d.vx=dir*kb*.5;gain(d,1);gain(a,1);EV('blk',a,d,ex);pop('BLOCK',px,py-40,'#4ff');if(tut&&d===A)tut.c.blk++;sfx('block');if(d.hp<=0)ko(d);return true}
if(gb&&d.st=='guard')pop('GUARD BREAK',px,py-50,'#ff6');
if(!jg&&d.st!='hurt'&&d.st!='grab'){a.combo=0;a.cs=0;a.lm=null}{const k=ex.sid||ex;if(a.lm!==k||!(ex.hits>1||ex.multi||ex.vol)){if(a.lm!=null)a.cs=(a.cs||0)+1;a.lm=k}}dm*=Math.max(CMIN,1-CSC*(a.cs||0))*(jg?JGD:1);d.hp-=dm;d.acc+=dm;fx2(a,d,dm,ex,px,py);limbHit(d,dm,lowFlag?'low':ex.hi?'hi':'mid',ex.cut);d.acct=100;if(ex.blunt){const g0=d.gauge;d.gauge=Math.max(0,g0-dm*ex.blunt);if(g0>=4&&d.gauge<(g0>>2)*4){pop('ゲージ削り',px,py-80,'#ffb84a');d.gfl=14}}else gain(d,1);gain(a,gg+(a.combo>=3?1:0));a.combo++;a.ct=60;if((a===A||VS2)&&ST&&!tut)ST.mc=Math.max(ST.mc,a.combo);if(a.combo>=3)sfx('combo',a.combo);if(a.combo==3)pop('COMBO!',a.x,py-70,'#ff6');
const mid=(ex.hits>1&&a.st=='atk'&&MV(a)===ex&&a.hit+1<ex.hits)||(ex.multi&&ex.mh+1<ex.multi)||ex.vol,kd=jg||lau||d.hp<=0||(!mid&&(d.acc>=d.c.kt*KTM||a.combo>=CMAX));d.sp=0;d.chain=0;
if(kd){if(jg){d.jg=(d.jg||0)+1;d.vy=Math.max(4,7-d.jg);d.vx=dir*3;pop('追撃!',px,py-60,'#ff6')}else{const up=lau&&ex.rise;d.jg=0;d.vy=up?10.5:lau?8:5.5;d.vx=dir*(up?2.5:kb+4);d.th=0;pop('DOWN!',px,py-60,'#f57')}d.st='fall';d.acc=0}else{d.st='hurt';d.stun=hs;d.vx=dir*kb;if(d.y>0)d.vy=4;if(ex.lift){d.vy=ex.lift;d.stun=Math.max(hs,26)}}
EV('hit',a,d,ex,kd);d.fl=10;burst(px,py,20);shake=Math.max(shake,lau?12:4);hstop=Math.max(hstop,lau?5:dm>=10?3:2);if(ex.cmx){ring(px,py,fcol(a),1);ring(px,py,'#ffffff',1);burst(px,py,30);shake=Math.max(shake,13);hstop=Math.max(hstop,6)}if(lau||d.hp<=0)ring(px,py,'#fff');if(tut&&a===A)tutHit(a);sfx(lau?'hitH':dm>=9?'hitM':'hitL');if(d.hp<=0)ko(d);return true}
function atk(f,t,fw){if(mode!='play')return false;const air=f.y>0;if(air&&t=='L')t='AL';else if(air&&t=='H')t='AH';else if(!air&&f.cr&&t=='L')t='CL';else if(!air&&f.cr&&t=='H')t='CH';else if(!air&&fw&&t=='L'&&f.c.M.L2)t='L2';else if(!air&&fw&&t=='H'&&f.c.M.H2)t='H2';const tk=f.stc>=2&&f.c.M[t+'@2']?t+'@2':f.stc&&f.c.M[t+'@']?t+'@':t,sm=f.c.M[tk]||{};if(f.cpu&&limbNG(f,f.c.M[tk],tk,0))return false;if(sm.kind=='limit'&&(f.stc>=2||f.hp<=1))return false;if(sm.req&&chst(f===A?B:A)<1)return false;if(f.legs>=2&&(air||LEG.includes(sm.ps||t)||sm.dvy>0||sm.dv2vy>0))return false;if(t=='T'&&f.arms>=2)return false;if(air&&(t=='T'||sm.kind=='t'||(!f.c.as&&(t=='W'||t=='E'||(t=='R'&&!sm.kind)||(t=='Q'&&sm.kind=='tr')))))return false;let cx=false;
if(f.st!='i'){if(!(f.st=='atk'&&f.hit&&(CN[f.ty.replace(/@.*/,'')]||[]).includes(t)))return false;if(t==f.ty.replace(/@.*/,'')&&(t=='L'||t=='CL'||t=='AL')&&f.chain>=3)return false;cx=true}
if(SP[t]){const sc=sm.cost!=null?sm.cost:SP[t];if(f.gauge<sc)return false;f.gauge-=sc;pop(sm.nm+'!',f.x,GY-f.y-120,'#ff6');if(tut&&f===A)tut.c.sp++;if(sc>=12){CI={t:46,nm:sm.nm.replace(/[(（].*/,''),c:f.c.col,left:f===A,gl:sm.self?1:0};hstop=Math.max(hstop,10)}}
f.chain=cx?f.chain+1:0;f.st='atk';f.ty=tk;f.at=0;f.lag=cx?0:Math.min(3,wLag(f,sm,t)+chLag(f,sm));if(cx)cFast(f,sm);if(sm.kind=='t')f.vx=f.face*THV;if(sm.minv)f.inv=Math.max(f.inv,sm.minv);if(sm.duck)f.cr=1;sfxAtk(t,sm);if(SP[t])spFx(f,(sm.cost!=null?sm.cost:SP[t])>=12);f.hit=0;f.hl=[];f.sp=0;f.gv=0;f.cg=0;f.cq=0;f.cm=0;f.cw=0;f.aid=++AID;if(cx)pop('LINK',f.x,GY-f.y-100,'#9cf');return true}
function cFast(f,P){const o=f===A?B:A;if(!o||!P||!P.su||f===o)return;const hu=o.st=='hurt',jg=o.st=='fall'&&o.y>JGY&&(o.jg||0)<JGM;if(!hu&&!jg)return;const lim=hu?o.stun-1-(P.kind=='p'?2:0):7,s2=Math.max(CSMIN,Math.min(P.su,lim));f.at=P.su-s2;if(!P.kind&&f.y<=0){const gap=Math.abs(o.x-f.x)-46;if(gap>0)f.vx=f.face*Math.min(8,gap*.2)}}
function doThrow(f,o,P){if(mode!='play')return;const dx=(o.x-f.x)*f.face;if(!(dx>-10&&dx<THR+P.tr&&o.y<=0&&o.st!='fall'&&o.st!='down'&&o.inv<=0))return;
if(o.st=='atk'&&o.ty=='T'){f.vx=-f.face*7;o.vx=-o.face*7;pop('TECH!',(f.x+o.x)/2,GY-100,'#5f5');sfx('tech');return}
if(o.st=='atk'&&o.at>=MV(o).su)return;
if(dx>THG){f.x=o.x-f.face*THG;f.vx=0}startGrab(f,o,P)}
function grabHit(f,o,P){if(o.y>0||o.st=='fall'||o.st=='down'||o.inv>0||mode!='play')return false;startGrab(f,o,{sp:1,nm:P.nm,self:P.self,heal:P.heal,td:P.d,vy:P.gvy!=null?P.gvy:8,vx:P.gvx!=null?P.gvx:7,gs:P.gs||0});f.vx=0;return true}

