function startDash(f,dir){const fw=dir==f.face;f.dsh=fw?13:9;f.dsd=dir;f.dfw=fw;f.vx=dir*(fw?9:8)*(f.legs?.7:1)*(1-.05*wLegU(f))*DSK(f);if(!fw)f.inv=Math.max(f.inv,5);if(f.c.mist){f.inv=Math.max(f.inv,fw?6:8);mistFx(f);sfx('tele');return}if(f.c.jetd){ring(f.x-dir*12,GY-f.y-52,fcol(f));sfx('shoot');return}burst(f.x,GY-4,200);sfx('dash')}
function lsp(f){return (1-.06*chst(f))*(1-.06*wLegU(f))*(f.c.n=='カグラ'&&!f.stc?1.1:1)*(f.legs?(1-.22*f.legs)*(f.legs>=2?.45:1):1)*(f.bz>0?1.2:1)*(f.c.stg&&f.stc>=2?1.15:1)*(f.gr?1+GRS*f.gr:1)}
const SPC=(f,t)=>{const m=f.c.M[t];return SP[t]&&(m&&m.cost!=null?m.cost:SP[t])};
/* v42 壊れた部位を使う技は当たらない: limbOf=その技(のn段目)が使う部位 0前腕 1後腕 2前脚 3後脚、-1=部位を使わない(投げ・体当たり・噛みつきなど) */
const NOLIMB=['BITE','ABITE','DRAIN','HEAD','SHOULDER','APRESS','GRABR','MIKIRI','SWAY'],LKIND=['t','stance','limit','buff'];
function limbOf(P,ty,hn){if(!P)return -1;const k=P.ps||ty;if(P.grab||P.noh||LKIND.includes(P.kind)||NOLIMB.includes(k))return -1;if(LEG.includes(k))return(k=='KICKS'||k=='AKICKS')&&hn%2?3:2;if(k=='STRAIGHT')return 1;if(k=='ONETWO'||k=='DEMP'||k=='RUSH')return hn%2?1:0;return 0}
const limbNG=(f,P,ty,hn)=>{if(tut||!f.pbk)return false;const i=limbOf(P,ty,hn);return i>=0&&!!f.pbk[i]};
function pm(a,ex){const P=a.st=='atk'?MV(a):null,leg=P&&ex===P&&LEG.includes(P.ps||a.ty);return Math.max(.5,1-.22*(leg?a.legs:a.arms))}
function limbHit(d,dm,zone,cut){cut=cut||1;if(tut||!d.pbk||d.hp<=0)return;const r=Math.random(),leg=zone=='low'?r<.85:zone=='hi'?r<.2:r<.5;let i=(leg?2:0)+(Math.random()<.5?0:1);if(d.pbk[i])i^=1;if(d.pbk[i])return;
const w0=wq(d,i);d.pd[i]+=Math.min(dm,d.mhp*.12)*cut;if(d.pd[i]<d.mhp*PT){const w1=wq(d,i);if(w1>w0)wound(d,i,w1)}if(d.pd[i]>=d.mhp*PT){d.pbk[i]=1;if((d===B||VS2)&&ST)ST.brk++;d.arms=d.pbk[0]+d.pbk[1];d.legs=d.pbk[2]+d.pbk[3];pop(LN[i]+(cut>1?'切断!':'破壊!'),d.x,GY-d.y-130,'#f33');tearOff(d,i);burst(d.x,GY-d.y-40,160);burst(d.x,GY-d.y-40,0);shake=Math.max(shake,14);sfx('limb');hstop=Math.max(hstop,9);ring(d.x,GY-d.y-40,'#f33',1);if(d.legs>=2)pop('立てない!',d.x,GY-d.y-150,'#f90');if(typeof BRK!='undefined')BRK[d===A?0:1]++}}
function tearOff(f,i){const leg=i>=2,L=LOOK[f.c.n],w=leg?[L.leg2[1]/2,L.leg2[1]/2,L.leg2[4]/2]:[L.arm2[1]/2,L.arm2[1]/2,L.arm2[4]/2],len=leg?27:23,ps=f.ps||{a1:[1.2,-.5],a2:[1.2,-.5],l1:[1.4,.3],l2:[1.8,.3]},ang=ps[['a1','a2','l1','l2'][i]],r=Math.random(),sc=f.c.sc||1;
DEB.push({x:f.x+f.face*(leg?8:16)*sc,y:GY-f.y-(leg?28:80)*sc,vx:-f.face*(3+r*3),vy:-(7+r*3),rot:ang[0]*f.face+(f.face<0?Math.PI:0),vr:(Math.random()-.5)*.6,l1:len*.45*sc,l2:len*sc,b:ang[1]*f.face,w0:(w[0]+w[1])*sc,w1:(w[1]+w[2])*sc,col:fcol(f),fill:L.fill||(leg?L.legs:L.arms)[0],t:0,rest:0,leg,mech:L.mech});
for(let k=0;k<3;k++)burst(f.x+f.face*10,GY-f.y-(leg?28:80),k?0:(L.mech?190:350))}
function updDeb(){for(const d of DEB){d.t++;if(!d.rest){d.vy+=.5;d.x+=d.vx;d.y+=d.vy;d.rot+=d.vr;if(d.t%3==0)parts.push({x:d.x,y:d.y,vx:(Math.random()-.5),vy:-.5,l:.6,h:d.mech?190:350});if(d.y>GY-4){d.y=GY-4;if(Math.abs(d.vy)>3)sfx('land');d.vy*=-.35;d.vx*=.55;d.vr*=.45;if(Math.abs(d.vy)<1.2){d.rest=1;d.vy=0}}if(d.x<XMIN-20||d.x>XMAX+20)d.vx*=-.5}}DEB=DEB.filter(d=>d.t<420)}
function drawDeb(){for(const d of DEB){const a=d.t>300?Math.max(0,1-(d.t-300)/120):1;g.save();g.translate(d.x,d.y);g.rotate(d.rot);g.globalAlpha=a;g.lineCap='round';const ex=d.l1,ey=0,hx=ex+Math.cos(d.b)*d.l2,hy=Math.sin(d.b)*d.l2,seg=(w,c)=>{g.strokeStyle=c;g.lineWidth=w;g.beginPath();g.moveTo(0,0);g.lineTo(ex,ey);g.stroke();g.lineWidth=w*.85;g.beginPath();g.moveTo(ex,ey);g.lineTo(hx,hy);g.stroke()};
g.globalAlpha=a*.25;seg(d.w0+9,d.col);g.globalAlpha=a;seg(d.w0+3.2,d.col);seg(d.w0,d.fill);g.fillStyle=d.mech?'#2ee6ff':'#ff5a5a';for(let k=-1;k<=1;k++){g.beginPath();g.moveTo(0,k*d.w0*.35);g.lineTo(-5-Math.abs(k)*2,k*d.w0*.5);g.lineTo(0,k*d.w0*.1);g.fill()}g.restore()}}
function stumble(f){if(f.st!='i'||tut)return;f.st='hurt';f.stun=18;f.vx=-f.face*2.5;f.dsh=0;pop('よろけ!',f.x,GY-f.y-120,'#f90');sfx('land')}
function brk(f,t){if(!f.pbk)return t;if(f.legs>=2&&f.y<=0&&f.st!='fall'&&f.st!='down'&&f.st!='grab'){const cw=Math.sin(f.wp*.9);t.lean=Math.max(t.lean,1.15);t.dy=(t.dy||0)*.3;if(f.st=='i'||f.st=='hurt'){t.a1=[.25+cw*.45,-.35-Math.max(0,cw)*.5];t.a2=[.25-cw*.45,-.35-Math.max(0,-cw)*.5]}}if(f.st=='atk'&&f.lag>0){const j=Math.sin(T*2.4)*.12;t.lean-=.1;if(LEG.includes(MV(f).ps||f.ty))t.l1=[t.l1[0]+j,t.l1[1]];else t.a1=[t.a1[0]+.35+j,t.a1[1]]}if(f.st!='i')return t;const b=f.pbk,s=Math.sin(T*.2)*.08;if(b[0])t.a1=[1.45+s,.2];if(b[1])t.a2=[1.55-s,.2];{const w=[0,1,2,3].map(i=>b[i]?0:wq(f,i)),tr=Math.sin(T*.9)*.05,dr=(v,h,k)=>[v[0]+(h[0]-v[0])*.3*k+tr*k,v[1]+(h[1]-v[1])*.3*k],wg=w[2]+w[3];if(w[0])t.a1=dr(t.a1,[1.45,.2],w[0]);if(w[1])t.a2=dr(t.a2,[1.55,.2],w[1]);if(wg&&!f.legs&&!f.cr&&f.y<=0){t.lean+=.03*wg;t.dy+=1.2*wg+(f.mv?Math.abs(Math.sin(f.wp))*2.2*wg:0)}}if(f.legs==1&&!f.cr&&f.y<=0){const wb=Math.sin(TT*.13)*.16+Math.sin(TT*.31)*.06;t.lean+=.1+wb;t.dy+=4+(f.mv?-Math.abs(Math.sin(f.wp*.8))*6:0);if(b[2]){t.l2=[1.6,.05];t.l1=[1.05,.4]}else{t.l1=[1.52,.05];t.l2=[1.95,.3]}if(!b[1])t.a2=[.2+wb*2,-.7];if(!b[0])t.a1=[.6-wb*2,-.4]}return t}
function startGrab(f,o,P){EV('grab',f,o,P);o.st='grab';o.gF=f;o.gP=P;o.gu=0;o.inv=GL+34;o.acc=0;o.vx=0;o.vy=0;o.sp=0;o.chain=0;o.face=-f.face;f.gv=1;hstop=5;ring(o.x,GY-50,'#ff6');if(tut&&f===A)tut.c.thr++;f.combo++;f.ct=60;gain(f,2);gain(o,1);o.fl=10;pop(P.nm+'!',o.x,GY-110,'#ff6');burst(o.x,GY-50,40);shake=6;sfx('grab')}
function grabTick(o){const F=o.gF,P=o.gP;if(!F||F.st!='atk'||o.gu>=GL){relGrab(o);return}o.gu++;const u=Math.min(1,o.gu/GL),s=P.gs||0,fc=F.face,PI=Math.PI;o.face=-fc;o.vx=0;o.vy=0;
if(s==0){o.x=F.x+fc*(22+8*u);o.y=8+84*Math.sin(u*1.57);o.th=-u*3.0}
else if(s==1){const a=u*6.28;o.x=F.x+fc*34*Math.cos(a);o.y=36+14*Math.sin(u*PI);o.th=-a}
else if(s==2){o.x=F.x+fc*(26+8*u);o.y=6+30*Math.sin(u*PI);o.th=-.6*u}
else if(s==3){o.x=F.x+fc*(26-52*u);o.y=10+64*Math.sin(u*PI);o.th=-u*PI}
else if(s==4){o.x=F.x+fc*22;o.y=34+3*Math.sin(o.gu*1.7);o.th=-.35}
else if(s==6){o.x=F.x+fc*19;o.y=5+Math.sin(o.gu*1.4);o.th=-.32;if(o.gu%4==0)parts.push({x:o.x-fc*4,y:GY-o.y-78,vx:-fc*(1+Math.random()),vy:-1,l:.8,h:345})}
else if(s==7){o.x=F.x+fc*26;o.y=4;o.th=0;if(o.gu%2==0)parts.push({x:o.x+(Math.random()-.5)*34,y:GY-10-Math.random()*80,vx:0,vy:-.8,l:.8,h:200})}
else{o.x=F.x+fc*(24+6*Math.sin(u*12));o.y=34+34*Math.abs(Math.sin(u*PI*2));o.th=-u*6.28}
o.y=Math.max(4,o.y)}
function relGrab(o){const F=o.gF,P=o.gP;o.gF=null;o.gu=0;if(!F||!P){o.st='i';o.th=0;o.y=0;return}const s=P.gs||0;o.acc=0;o.hp-=P.td*Math.max(.5,1-.22*F.arms);limbHit(o,P.td,'mid');if(P.self){const sd=F.mhp*P.self;F.hp=Math.max(1,F.hp-sd);burst(o.x,GY-o.y-30,190);burst(o.x,GY-o.y-30,0);ring(o.x,GY-o.y-30,'#ff3366',1);ring(o.x,GY-o.y-30,'#ffffff',1);sfx('det');pop('-'+Math.round(sd),F.x,GY-F.y-115,'#ff3366')}
if(P.heal){const h=Math.min(F.mhp-F.hp,P.td*P.heal*(F.c.mist&&o.bl>0?1.5:1));F.hp+=h;pop('+'+Math.round(h),F.x,GY-F.y-115,'#ff5a9a');if(F.c.mist)drainFx(F,o.x,GY-o.y-60)}
burst(o.x,GY-o.y-30,60);shake=P.self?20:s==0?16:11;sfx('slam');if(P.hx){shake=24;hstop=Math.max(hstop,10);ring(o.x,GY-o.y-30,'#ffd23c',1);ring(o.x,GY-o.y-30,'#ffffff',1);for(let k=0;k<3;k++)burst(o.x,GY-o.y-30,45);sfx('heat',4)}if(P.ice){shake=20;hstop=Math.max(hstop,8);ring(o.x,GY-o.y-40,'#cfe8ff',1);ring(o.x,GY-o.y-40,'#ffffff',1);for(let k=0;k<3;k++)burst(o.x,GY-o.y-40,k?200:0);sfx('chl',3)}
if(P.dn===false&&o.hp>0){o.st='hurt';o.stun=P.hs||50;o.inv=(P.hs||50)+22;o.vy=P.vy;o.vx=F.face*P.vx;o.th=0;o.spin=0}
else{o.st='fall';o.vy=s==0?-9:(s==3?-3:P.vy);o.vx=s==3?-F.face*4:(s==0?F.face*2:F.face*P.vx);o.spin=(s==1||s==5)?2:1;if(s==4||s==2||s==6||s==7)o.spin=0,o.th=0}
if(o.hp<=0)ko(o)}

