addEventListener('pointerdown',e=>{const[x,y]=pos(e);if(mode=='title'||mode=='menu'||mode=='end'||paused)sfx('ui');if(audHit(x,y)||langHit(x,y))return;if(paused){pauseClick(x,y);return}if((mode=='play'||mode=='ko'||mode=='intro')&&x>PB.x-10&&x<PB.x+PB.w+10&&y>PB.y-8&&y<PB.y+PB.h+10){paused=true;clrIn();sfx('ui');return}if(mode=='intro'&&introT>101){introT=101;return}if(tut&&mode=='play'&&trnHit(x,y))return;if(mode=='title'){if(y>TBY()&&y<TBY()+66)TBT.forEach((b,i)=>{if(x>b[2]&&x<b[2]+256){VS2=false;tutM=i==1;msub=0;mode='menu'}});else if(!touch&&y>TBY()+76&&y<TBY()+126&&x>W/2-262&&x<W/2+262)go2P();return}if(mode=='menu'){p2w(()=>menuClick(x,y));return}if(mode=='end'){endClick(x,y);return}
if(!touch&&mode=='play'&&!paused)spBarClick(x,y)});
const KM={ArrowLeft:'l',ArrowRight:'r',ArrowUp:'u',ArrowDown:'d'};
addEventListener('keydown',e=>{const k=e.key.length==1?e.key.toLowerCase():e.key;if(k=='m'){const on=AUD.bgm||AUD.se;AUD.bgm=AUD.se=on?0:1;saveAud();return}if(mode=='title'){if(k=='1'||k=='2'){VS2=false;tutM=k=='2';msub=0;mode='menu'}else if(k=='3'&&!touch)go2P();else if(k=='l')setLang(LANG=='en'?'ja':'en');return}if(mode=='menu'){if(k.startsWith('Arrow')||k==' ')e.preventDefault();p2w(()=>menuKey(k,e));return}if(mode=='end'){endKey(k);return}if((mode=='play'||mode=='ko'||mode=='intro')&&(k=='p'||k=='Escape')){paused=!paused;clrIn();return}if(paused){if(k=='Enter'||k==' ')paused=false;return}if(tut&&mode=='play'&&trnKey(k))return;if(mode=='intro'&&introT>101){introT=101;return}if(mode!='play')return;
if(k.startsWith('Arrow'))e.preventDefault();if(VS2){const q=vsKey(e,k);if(q){if(q[1]=='d')NF_INPUT.set(q[0],{[q[2]]:1});else{if(q[2]=='x'||q[2]=='a')NF_INPUT.set(q[0],{['h'+q[2]]:1});if(!e.repeat)act(q[2],0,q[0])}}return}if(KM[k])A.in[KM[k]]=1;if(k=='v')A.in.g=1;if(k=='x')A.in.hx=1;if(k=='a')A.in.ha=1;if(!e.repeat&&k.length==1&&'zxcasdf'.includes(k))act(k)});
addEventListener('keyup',e=>{if(VS2){const q=vsKey(e,e.key.length==1?e.key.toLowerCase():e.key);if(q&&q[1]=='d')NF_INPUT.set(q[0],{[q[2]]:0});else if(q&&(q[2]=='x'||q[2]=='a'))NF_INPUT.set(q[0],{['h'+q[2]]:0});return}if(KM[e.key])A.in[KM[e.key]]=0;const ku=e.key.toLowerCase();if(ku=='v')A.in.g=0;if(ku=='x')A.in.hx=0;if(ku=='a')A.in.ha=0});
addEventListener('contextmenu',e=>e.preventDefault());
if(touch){const ui=document.getElementById('ui'),dp=document.getElementById('dp'),ars={};dp.querySelectorAll('i').forEach(i=>ars[i.dataset.d]=i);let dpId=null,uiOn=false;
const dpSet=e=>{const r=dp.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),v={l:dx<-r.width*.13,r:dx>r.width*.13,u:dy<-r.height*.2,d:dy>r.height*.17};for(const k in v){if(A&&A.in)A.in[k]=v[k]?1:0;ars[{l:'l',r:'r',u:'u',d:'d'}[k]].classList.toggle('on',v[k])}};
const dpClr=()=>{dpId=null;['l','r','u','d'].forEach(k=>{if(A&&A.in)A.in[k]=0;ars[k].classList.remove('on')})};
dp.addEventListener('pointerdown',e=>{e.preventDefault();dpId=e.pointerId;try{dp.setPointerCapture(e.pointerId)}catch(x){}dpSet(e)});
dp.addEventListener('pointermove',e=>{if(e.pointerId===dpId)dpSet(e)});
['pointerup','pointercancel','lostpointercapture'].forEach(t=>dp.addEventListener(t,e=>{if(e.pointerId===dpId)dpClr()}));
const sb=[];ui.querySelectorAll('.b').forEach(b=>{const k=b.dataset.k;if(b.classList.contains('sp'))sb[' asdf'.indexOf(k)-1]=b;
b.addEventListener('pointerdown',e=>{e.preventDefault();try{b.setPointerCapture(e.pointerId)}catch(x){}b.classList.add('p');if(k=='v'){if(A&&A.in)A.in.g=1}else{if(A&&A.in&&(k=='x'||k=='a'))A.in['h'+k]=1;act(k)}});
['pointerup','pointercancel'].forEach(t=>b.addEventListener(t,()=>{b.classList.remove('p');if(A&&A.in){if(k=='v')A.in.g=0;if(k=='x'||k=='a')A.in['h'+k]=0}}))});
uiSync=()=>{const on=(mode=='play'||mode=='ko'||mode=='intro')&&!paused&&!SPECT;if(on!==uiOn){uiOn=on;ui.style.display=on?'block':'none';if(!on)dpClr()}if(!on||!A||!A.c)return;const M=A.c.M;['Q','W','E','R'].forEach((q,i)=>{const b=sb[i];if(!b)return;const nm=LANG=='en'?TR(spName(A,q)).slice(0,18):spName(A,q).slice(0,8),cs=SPC(A,q),ok=A.gauge>=cs&&!(A.c.stg&&q=='Q'&&A.stc>=2)&&!SPNG(A,q),hv=Math.min(cs,A.gauge),key=nm+'|'+cs+'|'+Math.floor(hv/2)+(ok?'':'x');if(b._k!==key){b._k=key;b.querySelector('small').textContent=nm;const n=Math.ceil(cs/4);let h='';if(!cs)h='<i class=t>'+TR('消費なし')+'</i>';else if(cs<4)h='<i'+(ok?' class=f':'')+'>◖</i>';else for(let j=0;j<n;j++)h+='<i'+(A.gauge>=(j+1)*4?' class=f':'')+'>●</i>';b.querySelector('b').innerHTML=h;b.classList.toggle('rdy',ok);b.classList.toggle('ng',!ok)}})}}
