function spawn(f,P){sfx('shoot');if(P.kind=='tr'){PJ=PJ.filter(p=>!(p.trap&&p.own===f));const x=Math.max(XMIN+10,Math.min(XMAX-10,f.x+f.face*P.dist));PJ.push({x,vx:0,h:6,r:P.r,d:P.d,own:f,n:1,trap:1,life:300,lau:P.lau,vis:P.vis,ch:P.ch});pop('設置!',x,GY-30,'#7dff5a')}
else{const sid=++SID;P.bl.forEach((b,bi)=>{const q={sid,x:Math.max(XMIN,Math.min(XMAX,(P.spr?(bi-(P.bl.length-1)/2)*P.spr:0)+f.x+f.face*(P.aim?Math.max(50,Math.min(270,((f===A?B:A).x-f.x)*f.face)):P.at!=null?P.at:30))),vx:b[0]*f.face,r:P.r,d:P.d,own:f,n:P.n,lau:P.lau,heal:P.heal,bleed:P.bleed,lift:P.lift,multi:P.multi,iv:P.iv,life:P.life,mh:0,cmx:P.cmx,ch:P.ch,tall:P.tall,vol:P.bl.length>1?1:0,vis:P.vis,cut:P.cut,wave:P.wave,home:P.home,low:P.low,cd:(P.dl||0)+(P.spr?bi*3:0)};PJ.push(Object.assign(q,{h:b[1]+f.y,vv:f.y>0?(b[2]||0):0}))})}}
function ai(f,o){const L=LV[lv],M=f.stc&&f.c.MA?f.c.MA:f.c.M,i=f.in={l:0,r:0,u:0,d:0,g:0},PR=PERS[f.c.n]||PD,rs=()=>Math.random()/PR.sm;if(T%90==0)f.pm=Math.random()<PR.rush?1:0;if(PR.rz&&PR.rz(f))f.pm=1;if(f.st=='atk'&&f.hit&&PR.ha)f.ra=PR.ha;if(f.c.adash&&galeAI(f,o))return;if(f.c.chill&&tsuAI(f,o))return;if(f.c.chgc&&blazeAI(f,o,i))return;if(f.c.n=='カグラ'&&kagAI(f,o))return;if(f.c.n=='イヴ'&&eveAI(f,o))return;if(f.c.mist&&vampAI(f,o))return;if(styleAI(f,o,PR))return;if(T%40==0)f.err=(Math.random()-.5)*2*L.err;const dx=o.x-f.x,d=Math.abs(dx)+f.err;
const P=o.st=='atk'?MV(o):null,inR=P&&(P.rg?d<P.rg+30:o.ty=='T'&&d<THR+(P.tr||0)+20),gd=()=>{i.g=1;if(P.low)i.d=1};
if(f.st=='guard'&&o.st=='atk'&&inR)gd();else if(inR&&f.st=='i'&&f.y<=0&&o.ty!='T'){const ttl=P.su-o.at+(o.lag||0);if(ttl>0&&ttl<=PW){if(Math.random()<L.pp*PR.gm)gd()}else if(Math.random()<L.bk*(ttl>0?.12:.3)*PR.gm){gd();i.ng=1}else if(P.hi&&Math.random()<L.bk*.15*PR.gm)i.d=1}
if(f.st=='atk'&&f.hit){const b=f.ty.replace(/@.*/,''),hc=o.st=='hurt'||(o.st=='fall'&&o.y>JGY&&(o.jg||0)<JGM),key=f.ty+f.chain;if(f.ck!==key){f.ck=key;f.cgo=Math.random()<[.1,.35,.6,.8,.95][lv]}
if(hc&&f.cgo&&Math.random()<.2+L.cb*2){const r=Math.random(),sp=()=>{for(const t of(lv>=3?'REWQ':'EWQ')){const m=M[t];if(m&&!m.noh&&!NOCB.includes(m.kind)&&f.gauge>=(m.cost!=null?m.cost:SP[t])&&atk(f,t))return true}return false};
if(b=='L'){if(f.chain<2&&r<.55)atk(f,'L');else if(r<.75)atk(f,'L',1)||atk(f,'H');else atk(f,'H',r<.9)}else if(b=='L2'){if(r<.6||!sp())atk(f,'H',r<.3)}else if(b=='CL'){if(f.chain<2&&r<.45)atk(f,'L');else if(r<.8)atk(f,'H');else{f.cr=0;atk(f,'H')}}else if(b=='AL'){atk(f,r<.5?'L':'H')}else sp()}
else if(!hc&&Math.random()<L.cb){const r=Math.random();if(b=='L'){if(r<.5)atk(f,'L');else if(r<.85)atk(f,'H');else atk(f,'Q')}}}
if(f.y>0&&f.st=='i'&&d<85&&Math.random()<.2*PR.am)atk(f,Math.random()<.5?'L':'H');
if(M.H.lift&&f.y<=0&&f.st=='i'&&o.y>15&&o.st=='hurt'&&d<90)i.u=1;if(f.c.dj&&f.y>0&&f.vy<2&&!f.dju&&Math.random()<.07)i.u=1;
if(f.st=='i'&&!i.g&&!i.d){const g=f.gauge,aq=M.Q.aq;
if(M.W.rise&&o.y>10&&d<70&&g>=8&&lv>=2&&rs()<.3)atk(f,'W');
else if(M.W.ctr&&o.st=='atk'&&d<95&&g>=8&&lv>=1&&rs()<.05)atk(f,'W');
else if(M.W.tp&&d>90&&g>=8&&lv>=1&&rs()<.008*lv)atk(f,'W');
else if(M.W.dvx&&!M.W.grab&&d>90&&d<200&&g>=8&&lv>=1&&rs()<.01*lv)atk(f,'W');
else if(M.W.kind=='p'&&d>70&&d<280&&g>=8&&lv>=1&&rs()<.008*lv)atk(f,'W');else if(M.E.dv2t&&d<220&&g>=12&&lv>=2&&rs()<.01*lv)atk(f,'E');else if(M.E.rg>100&&d>60&&d<150&&g>=12&&lv>=2&&rs()<.02*lv)atk(f,'E');
else if(M.E.kind=='buff'&&!f.bz&&g>=12&&d<220&&rs()<.01)atk(f,'E');else if(M.E.tp&&d>90&&g>=12&&rs()<.008*lv)atk(f,'E');
else if(d>aq[0]&&d<aq[1]&&g>=4&&rs()<(.008+.003*lv)*PR.qm)atk(f,'Q');
else if(o.st=='guard'&&d<THR+M.T.tr-6&&rs()<(L.tp+.01)*PR.tm)atk(f,'T');
else if(o.st=='guard'&&d<130&&g>=12&&lv>=3&&rs()<.03)atk(f,'E');
else if(g>=20&&!(f.c.stg&&f.stc>=2)&&d<(M.R.kind=='t'?70:M.R.kind?230:M.R.rg+30)&&lv>=3&&rs()<.02)atk(f,'R');
else if(d<THR+M.T.tr-10&&o.st=='i'&&Math.random()<L.tp*.5*PR.tm)atk(f,'T');
else{if(f.y<=0&&PJ.some(p=>p.own!==f&&!p.trap&&Math.abs(p.x-f.x)<170&&Math.abs(p.x-f.x)>50)&&Math.random()<L.dg)i.u=1;
else if(f.y<=0&&d>90&&d<230&&Math.random()<.004*(lv+1)*PR.jm)i.u=1;
if(f.cr&&d<74&&Math.random()<L.ag*2)atk(f,Math.random()<.5?'L':'H');
else if(f.ra>0){f.ra--;if(dx>0)i.l=1;else i.r=1}else if(d>(f.pm?66:PR.keep[1])){if(dx>0)i.r=1;else i.l=1;if(d>160&&f.dsh<=0&&f.y<=0&&f.st=='i'&&Math.random()<.005*(lv+1)*(PR.rush>.5?2:1))startDash(f,dx>0?1:-1)}else if(d<(f.pm?0:PR.keep[0])&&Math.random()<PR.rt){if(dx>0)i.l=1;else i.r=1;if(f.dsh<=0&&f.y<=0&&f.st=='i'&&Math.random()<.04)startDash(f,dx>0?-1:1)}else if(d<66&&Math.random()<.02+.008*lv)i.d=1;else if(d<90&&Math.random()<L.ag*PR.ag*(f.gAg||1))atk(f,Math.random()<.65?'L':'H',Math.random()<.4);else if(d<38&&Math.random()<.03){if(dx>0)i.l=1;else i.r=1}}}}
function step(f,o){f.ox=f.x;f.oy=f.y;if(f.ads>0&&f.st!='i'&&f.st!='atk')f.ads=0;const pl=mode=='play',Z={l:0,r:0,u:0,d:0,g:0};if(f.cpu&&pl)(f.ai||ai)(f,o);const I=pl?f.in:Z;
if(f.gcd>0)f.gcd--;if(f.dsh>0){f.dsh--;if(f.st=='i'&&f.y<=0){f.vx=f.dsd*(f.dfw?8.5:7.5)*(f.legs?.7:1)*(1-.05*wLegU(f))*(.5+.5*f.dsh/13)*DSK(f);if(f.c.jetd)parts.push({x:f.x-f.dsd*16,y:GY-f.y-56+Math.random()*10,vx:-f.dsd*(3+Math.random()*2),vy:(Math.random()-.5)*.8,l:.7,h:190});else if(T%3==0||(f.c.slide&&f.dfw))parts.push(f.c.slide&&f.dfw?{x:f.x-f.dsd*(8+T%3*7),y:GY-2,vx:-f.dsd*.4,vy:-.3,l:.9,h:200}:f.c.mist?{x:f.x,y:GY-30-Math.random()*50,vx:-f.dsd,vy:-1,l:.7,h:340}:{x:f.x-f.dsd*10,y:GY-3,vx:-f.dsd*1.5,vy:-.6,l:.7,h:220})}else f.dsh=0}if(f.bz>0)f.bz--;if(pl&&f.chv>0){if(typeof CHF!='undefined'&&chst(f))CHF++;if(f.cht>0)f.cht--;else{f.chv=Math.max(0,f.chv-CQD);if(f.chm&&f.chv<CQR)f.chm=0}}if(pl&&f.gr>0&&++f.grt>=GRI)gear(f,-1);if(f.inv>0)f.inv--;if(f.ct>0&&--f.ct==0)f.combo=0;if(f.acct>0&&--f.acct==0)f.acc=0;if(pl)tickFx(f,o);if(pl&&f.c.hunger&&!tut){if(f.hp>0&&f.hp<=f.mhp*.4){if(!f.hng){f.hng=1;shake=Math.max(shake,12);hstop=Math.max(hstop,8);ring(f.x,GY-f.y-50,'#ff2e2e',1);ring(f.x,GY-f.y-50,'#ffffff',1);for(let k=0;k<3;k++)burst(f.x,GY-f.y-50,k?0:10);sfx('aura');CI={t:46,nm:'餓狼覚醒',c:'#ff2e2e',left:f===A,gl:0}}f.bz=Math.max(f.bz,2)}else if(f.hp>f.mhp*.4)f.hng=0}if(pl&&f.c.stg&&f.hp>0){const r=f.hp/f.mhp,tg2=r<=.3?2:r<=.6?1:0;if(tg2>f.stc)eveUp(f,tg2,0)}
const air=f.y>0,sp=f.c.sp*(f.cpu&&!f.ai?LV[lv].sf:1)*lsp(f);f.mv=0;if(f.st!='i'&&f.st!='guard'&&f.st!='atk')f.cr=0;
if(f.st=='grab')grabTick(f);
else if(f.st=='hurt'){if(--f.stun<=0){f.st='i';o.combo=0}}
else if(f.st=='fall'){if(f.spin==2&&f.y>0)f.th-=.16;else if(!f.spin)f.th=Math.min(1.57,f.th+.22);if(f.y<=0&&f.vy<=0){if(f.spin){let m=f.th%6.2832;if(m>3.1416)m-=6.2832;if(m<-3.1416)m+=6.2832;f.th=m;f.spin=0}f.st='down';f.dn=42;f.vx*=.3}}
else if(f.st=='down'){const t0=f.th<0?-1.57:1.57;f.th+=(t0-f.th)*.4;if(--f.dn<=0&&!(mode=='ko'&&f===koV)){f.st='i';f.inv=24;f.th=0;f.jg=0;o.combo=0}}
else if(f.st=='atk'){const P0=f.c.M[f.ty];let hold=0;if(P0.chg&&!f.cq){f.cg=(f.cg||0)+1;if(f.lag<=0&&f.at>=P0.su-1){if(I[P0.chg]&&f.cg<CHGT+CHGA&&f.y<=0){hold=1;if(f.cg==CHGT){ring(f.x+f.face*16,GY-f.y-58,'#ffffff');ring(f.x+f.face*16,GY-f.y-58,fcol(f),1);sfx('chg')}}else{f.cq=1;f.cm=f.cg>=CHGT?1:0}}}if(hold);else if(f.lag>0)f.lag--;else f.at++;const P=MV(f),tot=P.su+P.ac+P.rc-(f.gr&&GRM.includes(f.ty)?Math.min(f.gr,Math.max(0,P.rc-2)):0);
const le=P.air?2:(P.landend?P.dv2t+2:0);if(le&&f.y<=0&&f.at>le)f.st='i';else{
if(P.kind=='t'){if(!f.sp&&f.at>=P.su){f.sp=1;doThrow(f,o,P)}}
else if(P.kind=='p'||P.kind=='tr'){if(!f.sp&&f.at>=P.su){f.sp=1;if(limbNG(f,P,f.ty,0))pop('不発',f.x,GY-f.y-125,'#9aa3b5');else spawn(f,P)}}
else if(P.kind=='buff'){if(!f.sp&&f.at>=P.su){f.sp=1;f.bz=P.dur;pop('狂化!',f.x,GY-f.y-125,'#f33');sfx('aura');burst(f.x,GY-f.y-50,0)}}
else if(P.kind=='stance'){if(!f.sp&&f.at>=P.su){f.sp=1;f.stc=f.stc?0:1;pop(f.stc?'抜刀':'納刀',f.x,GY-f.y-95,f.stc?'#ff9a8a':'#bfe4ff');sfx('tag');burst(f.x+f.face*14,GY-f.y-40,200)}}
else if(P.kind=='limit'){if(!f.sp&&f.at>=P.su){f.sp=1;eveUp(f,f.stc+1,1)}}
else{const hc=P.hits||1;
if(P.dv2t&&f.at==P.dv2t){f.vy=P.dv2vy;f.vx=P.dv2vx*f.face}if(f.at==P.su){if(P.muz){const mx=f.x+f.face*52,my=GY-f.y-62;burst(mx,my,190);burst(mx,my,0);ring(mx,my,fcol(f));shake=Math.max(shake,4)}if(P.dvy)f.vy=P.dvy;if(P.inv)f.inv=P.inv;if(P.tp){const dr=o.x>f.x?1:-1,mf=f.c.mist;mf?mistFx(f):burst(f.x,GY-f.y-50,120);let nx=o.x+dr*55;if(nx<XMIN||nx>XMAX)nx=o.x-dr*55;f.x=nx;f.ox=nx;f.face=o.x>f.x?1:-1;if(mf){mistFx(f);sfx('tele')}else burst(f.x,GY-f.y-50,120)}}
const ia=f.at>=P.su&&f.at<P.su+P.ac;if(ia&&P.jet)for(let k=0;k<2;k++)parts.push({x:f.x+(Math.random()-.5)*10,y:GY-f.y+2,vx:(Math.random()-.5)*1.5,vy:2+Math.random()*2,l:.8,h:190});
if(ia&&P.dvx&&(f.hit<hc||hc>1))f.vx=P.dvx*f.face;
if(ia&&!P.noh&&f.at==P.su&&limbNG(f,P,f.ty,0)&&(hc==1||limbNG(f,P,f.ty,1)))pop('空振り',f.x,GY-f.y-125,'#9aa3b5');
if(ia&&!P.noh&&(hc==1||f.hit<hc)&&(hc==1||(f.at-P.su)%P.iv==0)&&!limbNG(f,P,f.ty,hc==1?0:Math.floor((f.at-P.su)/P.iv))){for(const t of[o]){if(hc==1?f.hl.includes(t):f.hit>=hc)continue;lowFlag=!!P.low;const dx=(t.x-f.x)*f.face,dy=f.y-t.y,ix=dx>-12&&dx<P.rg+16,iy=(P.air?(dy>-10&&dy<95):(P.rise?Math.abs(dy)<110:(P.low?(t.y<25&&Math.abs(dy)<70):Math.abs(dy)<70)))&&!(P.hi&&t.cr);
if(ix&&iy&&(P.grab?grabHit(f,t,P):hitRes(f,t,P.d,P.hs,P.kb,P.g,P.lau&&f.hit+1>=hc,P.gb,P))){f.hit++;f.hl.push(t);if(P.pull&&(t.st=='hurt'||t.st=='guard')){t.vx=-f.face*Math.max(0,Math.abs(t.x-f.x)-46)*(t.st=='guard'?.1:.2);if(t.st=='hurt')pop('捕らえた!',t.x,GY-t.y-130,'#ff3d7f')}if(P.zan&&(hc==1||f.hit>=hc))SPX.push({k:'zan',x:t.x,y:GY-t.y-55,t:0,col:fcol(f),big:P.zan>1,dir:f.face});if(P.dvx&&hc==1)f.vx=0}lowFlag=false}}}
if(f.at>=tot)f.st='i'}}
else{f.cr=(I.d||f.legs>=2)&&!air?1:0;if(I.g&&!air&&f.gcd<=0&&f.arms<2){if(f.st!='guard'){f.st='guard';f.gt=I.ng?PW+1:0}else f.gt++}else if(f.st=='guard'){f.st='i';f.gcd=8}
if(f.st!='guard'){if(f.legs<2&&(air?f.c.adash&&!f.adu&&!(f.ads>0):!f.cr&&f.dsh<=0))for(const k of['l','r'])if(I[k]&&!f['p'+k]){if(f.lk==k&&T-f.lt<=14){if(air)airDash(f,k=='r'?1:-1);else startDash(f,k=='r'?1:-1);f.lk=''}else{f.lk=k;f.lt=T}}
const dd=f.dsh>0||f.ads>0?0:f.cr&&f.legs<2?0:(I.r?1:0)-(I.l?1:0);f.x+=dd*sp*(air?(f.c.dj?1:.7):1);f.mv=dd!=0;f.wp+=Math.abs(dd)*.25*(sp/4);if(I.u&&!air&&!f.cr&&f.legs<2){f.vy=f.c.jv*(f.legs?.85:1)*(1-.03*wLegU(f))*(1-.03*chst(f));sfx('jump')}else if(I.u&&air&&!f.pu&&f.c.dj&&!f.dju){f.vy=f.c.jv*.92;f.dju=1;burst(f.x,GY-f.y,60);sfx('jump')}if(!air)f.face=o.x>f.x?1:-1}}
if(f.hov>0)f.hov--;if(f.y>0||f.vy>0){if(f.ads>0){f.ads--;f.vy=0;f.vx=f.add*(f.adf?ADV:ADW)*(f.legs?.7:1)*(1-.05*wLegU(f));if(f.ads%3==0)ring(f.x-f.add*14,GY-f.y-8,fcol(f))}else{f.y+=f.vy;f.vy-=.7}if(f.c.hover&&f.y>0){if(f.fuel==null)f.fuel=80;if(I.u&&f.vy<-.9&&f.fuel>0&&(f.st=='i'||f.st=='atk')&&f.legs<2){f.vy=-.9;f.fuel--;f.hov=3;if(T%2==0)parts.push({x:f.x-f.face*8+(Math.random()-.5)*6,y:GY-f.y-22,vx:(Math.random()-.5),vy:2.5+Math.random()*2,l:.7,h:190})}}if(f.y<=0){if(f.vy<-6&&f.st!='fall')sfx('land');f.y=0;f.vy=0;f.dju=0;f.adu=0;f.ads=0;f.fuel=80;if(f.legs==1&&f.st=='i'&&Math.random()<.4)stumble(f)}}
if(f.legs==1&&f.st=='i'&&f.y<=0&&(f.mv||f.dsh>0)&&Math.random()<.006)stumble(f);
f.x+=f.vx;f.vx*=.8;f.x=Math.max(XMIN,Math.min(XMAX,f.x));if(f.dsh>0)f.mv=1;lerpP(f);f.pu=I.u;f.pl=I.l;f.pr=I.r;
const ph=(f.c.mist&&f.dsh>0)||(o.c.mist&&o.dsh>0)||(f.c.slide&&f.dsh>0&&f.dfw)||(o.c.slide&&o.dsh>0&&o.dfw);
if(!ph&&Math.abs(f.x-o.x)<30&&f.y<50&&o.y<50&&f.st!='down'&&o.st!='down'&&f.st!='grab'&&o.st!='grab'){const s=f.x<o.x?-1:1;f.x+=s*2;if(f.x<XMIN||f.x>XMAX)f.x-=s*2}}
function update(){if(mode=='play'&&hstop>0){hstop--;for(const q of[A,B]){q.ox=q.x;q.oy=q.y;q.pp=null}return}if(mode=='intro'){step(A,B);step(B,A);if(--introT==44)sfx('fight');else if(introT==100&&GR&&rn==1)sfx('round');if(introT<=0)mode='play';return}if(mode=='ko'){step(A,B);step(B,A);updDeb();if(--kt<=0){if(koFinal)mode='end';else resetRound()}return}T++;if(ST&&!tut)ST.fr++;if(A.bq&&!A.cpu){if(--A.bq.t<0)A.bq=null;else act(A.bq.k,1)}if(VS2&&B.bq){if(--B.bq.t<0)B.bq=null;else act(B.bq.k,1,1)}step(A,B);step(B,A);updProj();updDeb();if(tut)tutTick();else{if(rt<=600&&rt>0&&rt%60==0)sfx('tick');if(--rt<=0)timeUp()}}
function updProj(){for(const p of PJ){p.x+=p.vx;if(p.wave){p.ph=(p.ph||0)+.22;p.h+=Math.cos(p.ph)*p.wave}if(p.home){const t=p.own===A?B:A;if(t)p.h+=Math.max(-p.home,Math.min(p.home,t.y+55-p.h))}if(p.vv){p.h+=p.vv;if(p.h<-10)p.dead=1}const ds=[p.own===A?B:A];
if(p.trap){if(--p.life<=0){p.dead=1;continue}for(const d of ds)if(Math.abs(p.x-d.x)<p.r+14&&d.y<25&&hitRes(p.own,d,p.d,24,8,1,p.lau,0,p.ch?p:null)){p.dead=1;if(p.vis=='ice'){burst(p.x,GY-30,200);burst(p.x,GY-30,0)}pop('BOOM',p.x,GY-40,'#7dff5a');break}continue}
if(p.cd>0)p.cd--;else for(const d of(lowFlag=!!p.low,ds))if(Math.abs(p.x-d.x)<p.r+16&&p.h+(p.tall||0)>d.y-8&&p.h<d.y+(d.cr?52:95)&&hitRes(p.own,d,p.d,24,p.multi?1:10,1,p.lau&&(!p.multi||p.mh+1>=p.multi),0,p)){if(p.multi){p.mh++;d.x+=(p.x-d.x)*.35;d.vx=p.vx;p.cd=p.iv||7;if(p.mh>=p.multi)p.dead=1}else p.dead=1;break}
lowFlag=false;if(p.life!=null&&--p.life<=0)p.dead=1;
if(p.x<XMIN-300||p.x>XMAX+300)p.dead=1}
for(const p of PJ)for(const q of PJ)if(p!==q&&!p.trap&&!q.trap&&p.own!==q.own&&!p.dead&&!q.dead&&Math.abs(p.x-q.x)<p.r+q.r&&p.n>=q.n){p.n-=q.n;q.dead=1;pop('CLASH!',p.x,GY-80,'#4ff');if(p.n<=0)p.dead=1}
PJ=PJ.filter(p=>!p.dead)}
